# Generated by Django 5.0.4 on 2024-04-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='average_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='question',
            name='is_something',
            field=models.BooleanField(default=False),
        ),
    ]
