# Generated by Django 5.0.4 on 2024-04-12 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choice_question_vote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='chocie',
            new_name='choice',
        ),
    ]
